// <auto-generated />
using System;
using Haulio.FarmFresh.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Haulio.FarmFresh.Persistence.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fruit",
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Vegetable",
                            Name = "Vegetable"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bakery",
                            Name = "Bakery"
                        });
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactName = "Hafizhan Al Wafi",
                            ContactTitle = "Hafiz",
                            CustomerName = "Hafizhan Al Wafi"
                        });
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Strategy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Ripe blue grape bunch among grapevine leaves at vineyard in warm sunset sunlight. Beautiful clusters of ripening grapes.",
                            Name = "Ripe Blue Grape",
                            Price = 10000m,
                            Strategy = "Packet"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Spinach (Spinacia oleracea) is a leafy green flowering plant native to central and western Asia. It is of the order Caryophyllales, family Amaranthaceae, subfamily Chenopodioideae. Its leaves are a common edible vegetable consumed either fresh, or after storage using preservation techniques by canning, freezing, or dehydration. It may be eaten cooked or raw, and the taste differs considerably; the high oxalate content may be reduced by steaming.",
                            Name = "Spinach",
                            Price = 10000m,
                            Strategy = "Packet"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Capsicum ˈkæpsɪkəm' is a genus of flowering plants in the nightshade family Solanaceae, native to the Americas, cultivated worldwide for their chili pepper or bell pepper fruit.",
                            Name = "Capsicum",
                            Price = 12000m,
                            Strategy = "Packet"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "The tomato is the edible berry of the plant Solanum lycopersicum,[1][2] commonly known as the tomato plant. The species originated in western South America, Mexico, and Central America.[2][3] The Mexican Nahuatl word tomatl gave rise to the Spanish word tomate, from which the English word tomato derived.[3][4] Its domestication and use as a cultivated food may have originated with the indigenous peoples of Mexico.[2][5] The Aztecs used tomatoes in their cooking at the time of the Spanish conquest of the Aztec Empire, and after the Spanish encountered the tomato for the first time after their contact with the Aztecs, they brought the plant to Europe, in a widespread transfer of plants known as the Columbian exchange. From there, the tomato was introduced to other parts of the European-colonized world during the 16th century.[2]",
                            Name = "Tomato",
                            Price = 5000m,
                            Strategy = "Packet"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "a term used for a variety of baked, commonly flour-based food products.[2] The term is applied to two distinct products in North America and the United Kingdom,[3] and is also distinguished from U.S. versions in the Commonwealth of Nations and Europe.",
                            Name = "Biscuit",
                            Price = 10000m,
                            Strategy = "Packet"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "a staple food prepared from a dough of flour and water, usually by baking.",
                            Name = "Bread",
                            Price = 10000m,
                            Strategy = "Packet"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Ripe blue grape bunch among grapevine leaves at vineyard in warm sunset sunlight. Beautiful clusters of ripening grapes.",
                            Name = "Ripe Blue Grape",
                            Price = 50000m,
                            Strategy = "Packet of 1 Bundles"
                        });
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductID", "ImageUrl");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            ImageUrl = "/src/assets/res/Screen%203/Untitled-1.png"
                        },
                        new
                        {
                            ProductID = 1,
                            ImageUrl = "/src/assets/res/Screen%203/Untitled-3.png"
                        },
                        new
                        {
                            ProductID = 1,
                            ImageUrl = "/src/assets/res/Screen%203/Untitled-9.jpg"
                        },
                        new
                        {
                            ProductID = 2,
                            ImageUrl = "/src/assets/res/Screen%203/Untitled-5.png"
                        });
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.ProductMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayText")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProductMenus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayText = "On Sales!",
                            IsActive = true,
                            Position = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayText = "New",
                            IsActive = true,
                            Position = 2
                        },
                        new
                        {
                            Id = 3,
                            DisplayText = "Shop by Store",
                            IsActive = true,
                            Position = 3
                        },
                        new
                        {
                            Id = 4,
                            DisplayText = "Fruit & Veg",
                            IsActive = true,
                            Position = 4
                        },
                        new
                        {
                            Id = 5,
                            DisplayText = "Meat & Seafood",
                            IsActive = true,
                            Position = 5
                        },
                        new
                        {
                            Id = 6,
                            DisplayText = "Dairy and Chilled",
                            IsActive = true,
                            Position = 6
                        },
                        new
                        {
                            Id = 7,
                            DisplayText = "Bakery",
                            IsActive = true,
                            Position = 7
                        },
                        new
                        {
                            Id = 8,
                            DisplayText = "Beverages",
                            IsActive = true,
                            Position = 8
                        });
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = "Fresh"
                        },
                        new
                        {
                            Id = "Healthy"
                        },
                        new
                        {
                            Id = "New"
                        });
                });

            modelBuilder.Entity("ProductProductMenu", b =>
                {
                    b.Property<int>("ProductMenusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductMenusId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductProductMenu");

                    b.HasData(
                        new
                        {
                            ProductMenusId = 1,
                            ProductsId = 1
                        },
                        new
                        {
                            ProductMenusId = 1,
                            ProductsId = 2
                        },
                        new
                        {
                            ProductMenusId = 2,
                            ProductsId = 1
                        },
                        new
                        {
                            ProductMenusId = 3,
                            ProductsId = 3
                        },
                        new
                        {
                            ProductMenusId = 4,
                            ProductsId = 8
                        },
                        new
                        {
                            ProductMenusId = 4,
                            ProductsId = 1
                        });
                });

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductTag");
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Order", b =>
                {
                    b.HasOne("Haulio.FarmFresh.Domain.Entities.Customer", "Customers")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Haulio.FarmFresh.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Haulio.FarmFresh.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Product", b =>
                {
                    b.HasOne("Haulio.FarmFresh.Domain.Entities.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Haulio.FarmFresh.Domain.Entities.Supplier", null)
                        .WithMany("Products")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Haulio.FarmFresh.Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductID")
                        .HasConstraintName("FK_ProductImages_Product_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductProductMenu", b =>
                {
                    b.HasOne("Haulio.FarmFresh.Domain.Entities.ProductMenu", null)
                        .WithMany()
                        .HasForeignKey("ProductMenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Haulio.FarmFresh.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.HasOne("Haulio.FarmFresh.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Haulio.FarmFresh.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("Haulio.FarmFresh.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
